-- ИГРОКИ
CREATE TABLE IF NOT EXISTS players(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    chat_id INTEGER NOT NULL UNIQUE,
    X INTEGER NOT NULL DEFAULT 16,
    Y INTEGER NOT NULL DEFAULT 16,
    joined_at TEXT DEFAULT CURRENT_TIMESTAMP,
    coins_collected INTEGER DEFAULT 0
)